"""add share_tokens sleep_logs step_logs tables

Revision ID: d5aec59a4c58
Revises: c3b0d6f7a4f1
Create Date: 2026-06-09 15:11:22.619908

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5aec59a4c58'
down_revision: Union[str, None] = 'c3b0d6f7a4f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    document_category = postgresql.ENUM('medical_report', 'prescription', 'lab_report', 'insurance', 'imaging', 'other', name='document_category', schema='bionex')
    document_category.create(op.get_bind(), checkfirst=True)

    op.create_table('share_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['bionex.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='bionex'
    )
    op.create_index(op.f('ix_bionex_share_tokens_id'), 'share_tokens', ['id'], unique=False, schema='bionex')
    op.create_index(op.f('ix_bionex_share_tokens_token'), 'share_tokens', ['token'], unique=True, schema='bionex')
    op.create_index(op.f('ix_bionex_share_tokens_user_id'), 'share_tokens', ['user_id'], unique=False, schema='bionex')
    op.create_table('sleep_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('period_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sleep_type', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['bionex.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='bionex'
    )
    op.create_index('ix_sleep_logs_user_period', 'sleep_logs', ['user_id', 'period_from'], unique=False, schema='bionex')
    op.create_table('step_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('period_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['bionex.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='bionex'
    )
    op.create_index(op.f('ix_bionex_step_logs_user_id'), 'step_logs', ['user_id'], unique=False, schema='bionex')
    op.create_table('user_daily_health',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('sleep_quality', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('step_count', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['bionex.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'record_date'),
    schema='bionex'
    )
    op.drop_constraint(op.f('access_permissions_family_member_id_fkey'), 'access_permissions', type_='foreignkey')
    op.drop_constraint(op.f('access_permissions_patient_id_fkey'), 'access_permissions', type_='foreignkey')
    op.drop_constraint(op.f('access_permissions_granted_to_user_id_fkey'), 'access_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'access_permissions', 'users', ['granted_to_user_id'], ['id'], source_schema='bionex', referent_schema='bionex', ondelete='CASCADE')
    op.create_foreign_key(None, 'access_permissions', 'family_members', ['family_member_id'], ['id'], source_schema='bionex', referent_schema='bionex', ondelete='SET NULL')
    op.create_foreign_key(None, 'access_permissions', 'patients', ['patient_id'], ['id'], source_schema='bionex', referent_schema='bionex', ondelete='CASCADE')
    op.drop_constraint(op.f('api_keys_key_hash_key'), 'api_keys', type_='unique')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.create_index(op.f('ix_bionex_api_keys_id'), 'api_keys', ['id'], unique=False, schema='bionex')
    op.create_index(op.f('ix_bionex_api_keys_is_active'), 'api_keys', ['is_active'], unique=False, schema='bionex')
    op.create_index(op.f('ix_bionex_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True, schema='bionex')
    op.create_index(op.f('ix_bionex_api_keys_user_id'), 'api_keys', ['user_id'], unique=False, schema='bionex')
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], source_schema='bionex', referent_schema='bionex', ondelete='SET NULL')
    op.drop_constraint(op.f('doctor_access_logs_doctor_user_id_fkey'), 'doctor_access_logs', type_='foreignkey')
    op.drop_constraint(op.f('doctor_access_logs_access_permission_id_fkey'), 'doctor_access_logs', type_='foreignkey')
    op.drop_constraint(op.f('doctor_access_logs_patient_id_fkey'), 'doctor_access_logs', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_access_logs', 'access_permissions', ['access_permission_id'], ['id'], source_schema='bionex', referent_schema='bionex', ondelete='SET NULL')
    op.create_foreign_key(None, 'doctor_access_logs', 'users', ['doctor_user_id'], ['id'], source_schema='bionex', referent_schema='bionex', ondelete='CASCADE')
    op.create_foreign_key(None, 'doctor_access_logs', 'patients', ['patient_id'], ['id'], source_schema='bionex', referent_schema='bionex', ondelete='CASCADE')
    op.add_column('documents', sa.Column('category', sa.Enum('medical_report', 'prescription', 'lab_report', 'insurance', 'imaging', 'other', name='document_category'), server_default='other', nullable=False))
    op.add_column('documents', sa.Column('source_app', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('is_shared_upload', sa.Boolean(), server_default='false', nullable=False))
    op.drop_constraint(op.f('documents_owner_user_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['owner_user_id'], ['id'], source_schema='bionex', referent_schema='bionex', ondelete='CASCADE')
    op.drop_constraint(op.f('family_members_owner_patient_id_fkey'), 'family_members', type_='foreignkey')
    op.create_foreign_key(None, 'family_members', 'patients', ['owner_patient_id'], ['id'], source_schema='bionex', referent_schema='bionex', ondelete='CASCADE')
    op.drop_constraint(op.f('lab_orders_patient_id_fkey'), 'lab_orders', type_='foreignkey')
    op.drop_constraint(op.f('lab_orders_family_member_id_fkey'), 'lab_orders', type_='foreignkey')
    op.drop_constraint(op.f('lab_orders_lab_test_id_fkey'), 'lab_orders', type_='foreignkey')
    op.create_foreign_key(None, 'lab_orders', 'family_members', ['family_member_id'], ['id'], source_schema='bionex', referent_schema='bionex', ondelete='SET NULL')
    op.create_foreign_key(None, 'lab_orders', 'patients', ['patient_id'], ['id'], source_schema='bionex', referent_schema='bionex', ondelete='CASCADE')
    op.create_foreign_key(None, 'lab_orders', 'lab_tests', ['lab_test_id'], ['id'], source_schema='bionex', referent_schema='bionex', ondelete='RESTRICT')
    op.drop_index(op.f('ix_login_attempts_phone'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_timestamp'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_user_id'), table_name='login_attempts')
    op.create_index(op.f('ix_bionex_login_attempts_account_locked_until'), 'login_attempts', ['account_locked_until'], unique=False, schema='bionex')
    op.create_index(op.f('ix_bionex_login_attempts_id'), 'login_attempts', ['id'], unique=False, schema='bionex')
    op.create_index(op.f('ix_bionex_login_attempts_phone'), 'login_attempts', ['phone'], unique=False, schema='bionex')
    op.create_index(op.f('ix_bionex_login_attempts_timestamp'), 'login_attempts', ['timestamp'], unique=False, schema='bionex')
    op.create_index(op.f('ix_bionex_login_attempts_user_id'), 'login_attempts', ['user_id'], unique=False, schema='bionex')
    op.drop_constraint(op.f('medical_records_patient_id_fkey'), 'medical_records', type_='foreignkey')
    op.drop_constraint(op.f('medical_records_family_member_id_fkey'), 'medical_records', type_='foreignkey')
    op.create_foreign_key(None, 'medical_records', 'family_members', ['family_member_id'], ['id'], source_schema='bionex', referent_schema='bionex', ondelete='SET NULL')
    op.create_foreign_key(None, 'medical_records', 'patients', ['patient_id'], ['id'], source_schema='bionex', referent_schema='bionex', ondelete='CASCADE')
    op.drop_constraint(op.f('medications_family_member_id_fkey'), 'medications', type_='foreignkey')
    op.drop_constraint(op.f('medications_patient_id_fkey'), 'medications', type_='foreignkey')
    op.create_foreign_key(None, 'medications', 'patients', ['patient_id'], ['id'], source_schema='bionex', referent_schema='bionex', ondelete='CASCADE')
    op.create_foreign_key(None, 'medications', 'family_members', ['family_member_id'], ['id'], source_schema='bionex', referent_schema='bionex', ondelete='SET NULL')
    op.drop_index(op.f('ix_password_history_changed_at'), table_name='password_history')
    op.drop_index(op.f('ix_password_history_user_id'), table_name='password_history')
    op.create_index(op.f('ix_bionex_password_history_changed_at'), 'password_history', ['changed_at'], unique=False, schema='bionex')
    op.create_index(op.f('ix_bionex_password_history_id'), 'password_history', ['id'], unique=False, schema='bionex')
    op.create_index(op.f('ix_bionex_password_history_user_id'), 'password_history', ['user_id'], unique=False, schema='bionex')
    op.drop_constraint(op.f('patients_user_id_fkey'), 'patients', type_='foreignkey')
    op.create_foreign_key(None, 'patients', 'users', ['user_id'], ['id'], source_schema='bionex', referent_schema='bionex', ondelete='CASCADE')
    op.drop_constraint(op.f('payments_lab_order_id_fkey'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('payments_user_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'lab_orders', ['lab_order_id'], ['id'], source_schema='bionex', referent_schema='bionex', ondelete='SET NULL')
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'], source_schema='bionex', referent_schema='bionex', ondelete='CASCADE')
    op.drop_constraint(op.f('reminder_logs_reminder_id_fkey'), 'reminder_logs', type_='foreignkey')
    op.create_foreign_key(None, 'reminder_logs', 'reminders', ['reminder_id'], ['id'], source_schema='bionex', referent_schema='bionex', ondelete='CASCADE')
    op.drop_constraint(op.f('reminders_medication_id_fkey'), 'reminders', type_='foreignkey')
    op.create_foreign_key(None, 'reminders', 'medications', ['medication_id'], ['id'], source_schema='bionex', referent_schema='bionex', ondelete='CASCADE')
    op.drop_index(op.f('ix_totp_secrets_user_id'), table_name='totp_secrets')
    op.drop_constraint(op.f('totp_secrets_user_id_key'), 'totp_secrets', type_='unique')
    op.create_index(op.f('ix_bionex_totp_secrets_id'), 'totp_secrets', ['id'], unique=False, schema='bionex')
    op.create_index(op.f('ix_bionex_totp_secrets_user_id'), 'totp_secrets', ['user_id'], unique=True, schema='bionex')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bionex_totp_secrets_user_id'), table_name='totp_secrets', schema='bionex')
    op.drop_index(op.f('ix_bionex_totp_secrets_id'), table_name='totp_secrets', schema='bionex')
    op.create_unique_constraint(op.f('totp_secrets_user_id_key'), 'totp_secrets', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_totp_secrets_user_id'), 'totp_secrets', ['user_id'], unique=False)
    op.drop_constraint(None, 'reminders', schema='bionex', type_='foreignkey')
    op.create_foreign_key(op.f('reminders_medication_id_fkey'), 'reminders', 'medications', ['medication_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'reminder_logs', schema='bionex', type_='foreignkey')
    op.create_foreign_key(op.f('reminder_logs_reminder_id_fkey'), 'reminder_logs', 'reminders', ['reminder_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'payments', schema='bionex', type_='foreignkey')
    op.drop_constraint(None, 'payments', schema='bionex', type_='foreignkey')
    op.create_foreign_key(op.f('payments_user_id_fkey'), 'payments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('payments_lab_order_id_fkey'), 'payments', 'lab_orders', ['lab_order_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'patients', schema='bionex', type_='foreignkey')
    op.create_foreign_key(op.f('patients_user_id_fkey'), 'patients', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_bionex_password_history_user_id'), table_name='password_history', schema='bionex')
    op.drop_index(op.f('ix_bionex_password_history_id'), table_name='password_history', schema='bionex')
    op.drop_index(op.f('ix_bionex_password_history_changed_at'), table_name='password_history', schema='bionex')
    op.create_index(op.f('ix_password_history_user_id'), 'password_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_password_history_changed_at'), 'password_history', ['changed_at'], unique=False)
    op.drop_constraint(None, 'medications', schema='bionex', type_='foreignkey')
    op.drop_constraint(None, 'medications', schema='bionex', type_='foreignkey')
    op.create_foreign_key(op.f('medications_patient_id_fkey'), 'medications', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('medications_family_member_id_fkey'), 'medications', 'family_members', ['family_member_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'medical_records', schema='bionex', type_='foreignkey')
    op.drop_constraint(None, 'medical_records', schema='bionex', type_='foreignkey')
    op.create_foreign_key(op.f('medical_records_family_member_id_fkey'), 'medical_records', 'family_members', ['family_member_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('medical_records_patient_id_fkey'), 'medical_records', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_bionex_login_attempts_user_id'), table_name='login_attempts', schema='bionex')
    op.drop_index(op.f('ix_bionex_login_attempts_timestamp'), table_name='login_attempts', schema='bionex')
    op.drop_index(op.f('ix_bionex_login_attempts_phone'), table_name='login_attempts', schema='bionex')
    op.drop_index(op.f('ix_bionex_login_attempts_id'), table_name='login_attempts', schema='bionex')
    op.drop_index(op.f('ix_bionex_login_attempts_account_locked_until'), table_name='login_attempts', schema='bionex')
    op.create_index(op.f('ix_login_attempts_user_id'), 'login_attempts', ['user_id'], unique=False)
    op.create_index(op.f('ix_login_attempts_timestamp'), 'login_attempts', ['timestamp'], unique=False)
    op.create_index(op.f('ix_login_attempts_phone'), 'login_attempts', ['phone'], unique=False)
    op.drop_constraint(None, 'lab_orders', schema='bionex', type_='foreignkey')
    op.drop_constraint(None, 'lab_orders', schema='bionex', type_='foreignkey')
    op.drop_constraint(None, 'lab_orders', schema='bionex', type_='foreignkey')
    op.create_foreign_key(op.f('lab_orders_lab_test_id_fkey'), 'lab_orders', 'lab_tests', ['lab_test_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('lab_orders_family_member_id_fkey'), 'lab_orders', 'family_members', ['family_member_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('lab_orders_patient_id_fkey'), 'lab_orders', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'family_members', schema='bionex', type_='foreignkey')
    op.create_foreign_key(op.f('family_members_owner_patient_id_fkey'), 'family_members', 'patients', ['owner_patient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'documents', schema='bionex', type_='foreignkey')
    op.create_foreign_key(op.f('documents_owner_user_id_fkey'), 'documents', 'users', ['owner_user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('documents', 'is_shared_upload')
    op.drop_column('documents', 'source_app')
    op.drop_column('documents', 'category')
    document_category = postgresql.ENUM('medical_report', 'prescription', 'lab_report', 'insurance', 'imaging', 'other', name='document_category', schema='bionex')
    document_category.drop(op.get_bind(), checkfirst=True)
    op.drop_constraint(None, 'doctor_access_logs', schema='bionex', type_='foreignkey')
    op.drop_constraint(None, 'doctor_access_logs', schema='bionex', type_='foreignkey')
    op.drop_constraint(None, 'doctor_access_logs', schema='bionex', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_access_logs_patient_id_fkey'), 'doctor_access_logs', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('doctor_access_logs_access_permission_id_fkey'), 'doctor_access_logs', 'access_permissions', ['access_permission_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('doctor_access_logs_doctor_user_id_fkey'), 'doctor_access_logs', 'users', ['doctor_user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'audit_logs', schema='bionex', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_bionex_api_keys_user_id'), table_name='api_keys', schema='bionex')
    op.drop_index(op.f('ix_bionex_api_keys_key_hash'), table_name='api_keys', schema='bionex')
    op.drop_index(op.f('ix_bionex_api_keys_is_active'), table_name='api_keys', schema='bionex')
    op.drop_index(op.f('ix_bionex_api_keys_id'), table_name='api_keys', schema='bionex')
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=False)
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_unique_constraint(op.f('api_keys_key_hash_key'), 'api_keys', ['key_hash'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'access_permissions', schema='bionex', type_='foreignkey')
    op.drop_constraint(None, 'access_permissions', schema='bionex', type_='foreignkey')
    op.drop_constraint(None, 'access_permissions', schema='bionex', type_='foreignkey')
    op.create_foreign_key(op.f('access_permissions_granted_to_user_id_fkey'), 'access_permissions', 'users', ['granted_to_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('access_permissions_patient_id_fkey'), 'access_permissions', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('access_permissions_family_member_id_fkey'), 'access_permissions', 'family_members', ['family_member_id'], ['id'], ondelete='SET NULL')
    op.drop_table('user_daily_health', schema='bionex')
    op.drop_index(op.f('ix_bionex_step_logs_user_id'), table_name='step_logs', schema='bionex')
    op.drop_table('step_logs', schema='bionex')
    op.drop_index('ix_sleep_logs_user_period', table_name='sleep_logs', schema='bionex')
    op.drop_table('sleep_logs', schema='bionex')
    op.drop_index(op.f('ix_bionex_share_tokens_user_id'), table_name='share_tokens', schema='bionex')
    op.drop_index(op.f('ix_bionex_share_tokens_token'), table_name='share_tokens', schema='bionex')
    op.drop_index(op.f('ix_bionex_share_tokens_id'), table_name='share_tokens', schema='bionex')
    op.drop_table('share_tokens', schema='bionex')
    # ### end Alembic commands ###
