"""initial_schema

Revision ID: f9b39b741c92
Revises:
Create Date: 2026-04-08 09:13:48.468570

"""

from typing import Sequence, Union

import sqlalchemy as sa
import app.models.base
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f9b39b741c92"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lab_tests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=255), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_lab_tests_category"),
        "lab_tests",
        ["category"],
        unique=False,
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_lab_tests_id"),
        "lab_tests",
        ["id"],
        unique=False,
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_lab_tests_name"),
        "lab_tests",
        ["name"],
        unique=False,
        schema="bionex",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("PATIENT", "DOCTOR", "ADMIN", name="userrole"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_users_email"), "users", ["email"], unique=True, schema="bionex"
    )
    op.create_index(
        op.f("ix_bionex_users_id"), "users", ["id"], unique=False, schema="bionex"
    )
    op.create_index(
        op.f("ix_bionex_users_phone"), "users", ["phone"], unique=True, schema="bionex"
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["bionex.users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_audit_logs_action"),
        "audit_logs",
        ["action"],
        unique=False,
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_audit_logs_created_at"),
        "audit_logs",
        ["created_at"],
        unique=False,
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_audit_logs_id"),
        "audit_logs",
        ["id"],
        unique=False,
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_audit_logs_resource_type"),
        "audit_logs",
        ["resource_type"],
        unique=False,
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_audit_logs_user_id"),
        "audit_logs",
        ["user_id"],
        unique=False,
        schema="bionex",
    )
    op.create_table(
        "patients",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column(
            "gender", sa.Enum("MALE", "FEMALE", "OTHER", name="gender"), nullable=True
        ),
        sa.Column("blood_group", sa.String(length=10), nullable=True),
        sa.Column(
            "address", app.models.base.EncryptedString(length=1000), nullable=True
        ),
        sa.Column("emergency_contact_name", sa.String(length=255), nullable=True),
        sa.Column(
            "emergency_contact_phone",
            app.models.base.EncryptedString(length=30),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["bionex.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_patients_id"), "patients", ["id"], unique=False, schema="bionex"
    )
    op.create_index(
        op.f("ix_bionex_patients_user_id"),
        "patients",
        ["user_id"],
        unique=True,
        schema="bionex",
    )
    op.create_table(
        "family_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_patient_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "relation",
            sa.Enum(
                "FATHER",
                "MOTHER",
                "SPOUSE",
                "CHILD",
                "SIBLING",
                "GRANDPARENT",
                "OTHER",
                name="relation",
            ),
            nullable=False,
        ),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("gender", sa.String(length=10), nullable=True),
        sa.Column("blood_group", sa.String(length=10), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_patient_id"], ["bionex.patients.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_family_members_id"),
        "family_members",
        ["id"],
        unique=False,
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_family_members_owner_patient_id"),
        "family_members",
        ["owner_patient_id"],
        unique=False,
        schema="bionex",
    )
    op.create_table(
        "access_permissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("family_member_id", sa.UUID(), nullable=True),
        sa.Column("granted_to_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "initiated_by",
            sa.Enum("PATIENT", "DOCTOR", name="initiatedby"),
            nullable=False,
        ),
        sa.Column(
            "request_status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "REVOKED",
                "EXPIRED",
                name="requeststatus",
            ),
            nullable=False,
        ),
        sa.Column("access_token", sa.String(length=500), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scope", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_member_id"], ["bionex.family_members.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["granted_to_user_id"], ["bionex.users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["bionex.patients.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_access_permissions_access_token"),
        "access_permissions",
        ["access_token"],
        unique=True,
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_access_permissions_family_member_id"),
        "access_permissions",
        ["family_member_id"],
        unique=False,
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_access_permissions_granted_to_user_id"),
        "access_permissions",
        ["granted_to_user_id"],
        unique=False,
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_access_permissions_id"),
        "access_permissions",
        ["id"],
        unique=False,
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_access_permissions_patient_id"),
        "access_permissions",
        ["patient_id"],
        unique=False,
        schema="bionex",
    )
    op.create_table(
        "lab_orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("family_member_id", sa.UUID(), nullable=True),
        sa.Column("lab_test_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "BOOKED",
                "SAMPLE_COLLECTED",
                "PROCESSING",
                "COMPLETED",
                "CANCELLED",
                name="orderstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "collection_type",
            sa.Enum("HOME", "LAB", name="collectiontype"),
            nullable=False,
        ),
        sa.Column("scheduled_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "collection_address",
            app.models.base.EncryptedString(length=1000),
            nullable=True,
        ),
        sa.Column(
            "report_url", app.models.base.EncryptedString(length=2000), nullable=True
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_member_id"], ["bionex.family_members.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["lab_test_id"], ["bionex.lab_tests.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["bionex.patients.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_lab_orders_family_member_id"),
        "lab_orders",
        ["family_member_id"],
        unique=False,
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_lab_orders_id"),
        "lab_orders",
        ["id"],
        unique=False,
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_lab_orders_lab_test_id"),
        "lab_orders",
        ["lab_test_id"],
        unique=False,
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_lab_orders_patient_id"),
        "lab_orders",
        ["patient_id"],
        unique=False,
        schema="bionex",
    )
    op.create_table(
        "medical_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("family_member_id", sa.UUID(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "PRESCRIPTION",
                "LAB_REPORT",
                "DIAGNOSIS",
                "IMAGING",
                "VACCINATION",
                "OTHER",
                name="recordtype",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("notes", app.models.base.EncryptedString(length=5000), nullable=True),
        sa.Column(
            "file_url", app.models.base.EncryptedString(length=2000), nullable=True
        ),
        sa.Column("record_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_member_id"], ["bionex.family_members.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["bionex.patients.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_medical_records_family_member_id"),
        "medical_records",
        ["family_member_id"],
        unique=False,
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_medical_records_id"),
        "medical_records",
        ["id"],
        unique=False,
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_medical_records_patient_id"),
        "medical_records",
        ["patient_id"],
        unique=False,
        schema="bionex",
    )
    op.create_table(
        "medications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("family_member_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("dosage", sa.String(length=255), nullable=True),
        sa.Column("frequency", sa.String(length=255), nullable=True),
        sa.Column("instructions", sa.String(length=1000), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_member_id"], ["bionex.family_members.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["bionex.patients.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_medications_family_member_id"),
        "medications",
        ["family_member_id"],
        unique=False,
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_medications_id"),
        "medications",
        ["id"],
        unique=False,
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_medications_patient_id"),
        "medications",
        ["patient_id"],
        unique=False,
        schema="bionex",
    )
    op.create_table(
        "doctor_access_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("doctor_user_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("access_permission_id", sa.UUID(), nullable=True),
        sa.Column("session_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("session_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("records_accessed", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["access_permission_id"],
            ["bionex.access_permissions.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["doctor_user_id"], ["bionex.users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["bionex.patients.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_doctor_access_logs_access_permission_id"),
        "doctor_access_logs",
        ["access_permission_id"],
        unique=False,
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_doctor_access_logs_doctor_user_id"),
        "doctor_access_logs",
        ["doctor_user_id"],
        unique=False,
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_doctor_access_logs_id"),
        "doctor_access_logs",
        ["id"],
        unique=False,
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_doctor_access_logs_patient_id"),
        "doctor_access_logs",
        ["patient_id"],
        unique=False,
        schema="bionex",
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("lab_order_id", sa.UUID(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "COMPLETED", "FAILED", "REFUNDED", name="paymentstatus"),
            nullable=False,
        ),
        sa.Column("payment_method", sa.String(length=50), nullable=True),
        sa.Column("transaction_id", sa.String(length=255), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["lab_order_id"], ["bionex.lab_orders.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["bionex.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_payments_id"), "payments", ["id"], unique=False, schema="bionex"
    )
    op.create_index(
        op.f("ix_bionex_payments_lab_order_id"),
        "payments",
        ["lab_order_id"],
        unique=True,
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_payments_transaction_id"),
        "payments",
        ["transaction_id"],
        unique=True,
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_payments_user_id"),
        "payments",
        ["user_id"],
        unique=False,
        schema="bionex",
    )
    op.create_table(
        "reminders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("medication_id", sa.UUID(), nullable=False),
        sa.Column("time", sa.Time(), nullable=False),
        sa.Column(
            "frequency",
            sa.Enum("DAILY", "WEEKLY", "CUSTOM", name="reminderfrequency"),
            nullable=False,
        ),
        sa.Column("days_of_week", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["medication_id"], ["bionex.medications.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_reminders_id"),
        "reminders",
        ["id"],
        unique=False,
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_reminders_medication_id"),
        "reminders",
        ["medication_id"],
        unique=False,
        schema="bionex",
    )
    op.create_table(
        "reminder_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("reminder_id", sa.UUID(), nullable=False),
        sa.Column("scheduled_date", sa.String(length=20), nullable=False),
        sa.Column(
            "status",
            sa.Enum("TAKEN", "MISSED", "SKIPPED", name="reminderstatus"),
            nullable=False,
        ),
        sa.Column("logged_at", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["reminder_id"], ["bionex.reminders.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_reminder_logs_id"),
        "reminder_logs",
        ["id"],
        unique=False,
        schema="bionex",
    )
    op.create_index(
        op.f("ix_bionex_reminder_logs_reminder_id"),
        "reminder_logs",
        ["reminder_id"],
        unique=False,
        schema="bionex",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_bionex_reminder_logs_reminder_id"),
        table_name="reminder_logs",
        schema="bionex",
    )
    op.drop_index(
        op.f("ix_bionex_reminder_logs_id"), table_name="reminder_logs", schema="bionex"
    )
    op.drop_table("reminder_logs", schema="bionex")
    op.drop_index(
        op.f("ix_bionex_reminders_medication_id"),
        table_name="reminders",
        schema="bionex",
    )
    op.drop_index(
        op.f("ix_bionex_reminders_id"), table_name="reminders", schema="bionex"
    )
    op.drop_table("reminders", schema="bionex")
    op.drop_index(
        op.f("ix_bionex_payments_user_id"), table_name="payments", schema="bionex"
    )
    op.drop_index(
        op.f("ix_bionex_payments_transaction_id"),
        table_name="payments",
        schema="bionex",
    )
    op.drop_index(
        op.f("ix_bionex_payments_lab_order_id"), table_name="payments", schema="bionex"
    )
    op.drop_index(op.f("ix_bionex_payments_id"), table_name="payments", schema="bionex")
    op.drop_table("payments", schema="bionex")
    op.drop_index(
        op.f("ix_bionex_doctor_access_logs_patient_id"),
        table_name="doctor_access_logs",
        schema="bionex",
    )
    op.drop_index(
        op.f("ix_bionex_doctor_access_logs_id"),
        table_name="doctor_access_logs",
        schema="bionex",
    )
    op.drop_index(
        op.f("ix_bionex_doctor_access_logs_doctor_user_id"),
        table_name="doctor_access_logs",
        schema="bionex",
    )
    op.drop_index(
        op.f("ix_bionex_doctor_access_logs_access_permission_id"),
        table_name="doctor_access_logs",
        schema="bionex",
    )
    op.drop_table("doctor_access_logs", schema="bionex")
    op.drop_index(
        op.f("ix_bionex_medications_patient_id"),
        table_name="medications",
        schema="bionex",
    )
    op.drop_index(
        op.f("ix_bionex_medications_id"), table_name="medications", schema="bionex"
    )
    op.drop_index(
        op.f("ix_bionex_medications_family_member_id"),
        table_name="medications",
        schema="bionex",
    )
    op.drop_table("medications", schema="bionex")
    op.drop_index(
        op.f("ix_bionex_medical_records_patient_id"),
        table_name="medical_records",
        schema="bionex",
    )
    op.drop_index(
        op.f("ix_bionex_medical_records_id"),
        table_name="medical_records",
        schema="bionex",
    )
    op.drop_index(
        op.f("ix_bionex_medical_records_family_member_id"),
        table_name="medical_records",
        schema="bionex",
    )
    op.drop_table("medical_records", schema="bionex")
    op.drop_index(
        op.f("ix_bionex_lab_orders_patient_id"),
        table_name="lab_orders",
        schema="bionex",
    )
    op.drop_index(
        op.f("ix_bionex_lab_orders_lab_test_id"),
        table_name="lab_orders",
        schema="bionex",
    )
    op.drop_index(
        op.f("ix_bionex_lab_orders_id"), table_name="lab_orders", schema="bionex"
    )
    op.drop_index(
        op.f("ix_bionex_lab_orders_family_member_id"),
        table_name="lab_orders",
        schema="bionex",
    )
    op.drop_table("lab_orders", schema="bionex")
    op.drop_index(
        op.f("ix_bionex_access_permissions_patient_id"),
        table_name="access_permissions",
        schema="bionex",
    )
    op.drop_index(
        op.f("ix_bionex_access_permissions_id"),
        table_name="access_permissions",
        schema="bionex",
    )
    op.drop_index(
        op.f("ix_bionex_access_permissions_granted_to_user_id"),
        table_name="access_permissions",
        schema="bionex",
    )
    op.drop_index(
        op.f("ix_bionex_access_permissions_family_member_id"),
        table_name="access_permissions",
        schema="bionex",
    )
    op.drop_index(
        op.f("ix_bionex_access_permissions_access_token"),
        table_name="access_permissions",
        schema="bionex",
    )
    op.drop_table("access_permissions", schema="bionex")
    op.drop_index(
        op.f("ix_bionex_family_members_owner_patient_id"),
        table_name="family_members",
        schema="bionex",
    )
    op.drop_index(
        op.f("ix_bionex_family_members_id"),
        table_name="family_members",
        schema="bionex",
    )
    op.drop_table("family_members", schema="bionex")
    op.drop_index(
        op.f("ix_bionex_patients_user_id"), table_name="patients", schema="bionex"
    )
    op.drop_index(op.f("ix_bionex_patients_id"), table_name="patients", schema="bionex")
    op.drop_table("patients", schema="bionex")
    op.drop_index(
        op.f("ix_bionex_audit_logs_user_id"), table_name="audit_logs", schema="bionex"
    )
    op.drop_index(
        op.f("ix_bionex_audit_logs_resource_type"),
        table_name="audit_logs",
        schema="bionex",
    )
    op.drop_index(
        op.f("ix_bionex_audit_logs_id"), table_name="audit_logs", schema="bionex"
    )
    op.drop_index(
        op.f("ix_bionex_audit_logs_created_at"),
        table_name="audit_logs",
        schema="bionex",
    )
    op.drop_index(
        op.f("ix_bionex_audit_logs_action"), table_name="audit_logs", schema="bionex"
    )
    op.drop_table("audit_logs", schema="bionex")
    op.drop_index(op.f("ix_bionex_users_phone"), table_name="users", schema="bionex")
    op.drop_index(op.f("ix_bionex_users_id"), table_name="users", schema="bionex")
    op.drop_index(op.f("ix_bionex_users_email"), table_name="users", schema="bionex")
    op.drop_table("users", schema="bionex")
    op.drop_index(
        op.f("ix_bionex_lab_tests_name"), table_name="lab_tests", schema="bionex"
    )
    op.drop_index(
        op.f("ix_bionex_lab_tests_id"), table_name="lab_tests", schema="bionex"
    )
    op.drop_index(
        op.f("ix_bionex_lab_tests_category"), table_name="lab_tests", schema="bionex"
    )
    op.drop_table("lab_tests", schema="bionex")
    # ### end Alembic commands ###
